### ISSUE TITLE
./manage.py runjob submit does not send any e-mail

### ISSUE THREAD

**Issue by torresmarcelo** [dokterbob/django-newsletter#10]
Everything seems to be properly installed. There is a message in the queue but nothing happens when I run the above command.

**Comment by benye** [comment]
I lost a lot of time because I didn't see this. My runjob submit was not doing anything and it was frustrating. It would help to mention this in the readthedocs or the README. Great app

**Comment by dokterbob** [comment]
Thanks for the feedback. I woud actually prefer fixing the UI-issue (making the button more accessible) rather than endorsing a workaround.

**Comment by symbolic-ac** [comment]
Can we add submit in action dropdown ?
![Screenshot from 2021-02-26 19-36-54](https://user-images.githubusercontent.com/73990887/109310140-28b8d380-786a-11eb-80ea-0f79b5ca0ab3.png)
