### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by dokterbob** [dokterbob/django-newsletter#102]
The Django part is clear-cut: https://docs.djangoproject.com/en/1.9/topics/python3/

Some dependencies are known to be outdated/unmaintained and do not support Python 3:
- [x] [vobject](http://vobject.skyhouseconsulting.com/)
- [ ] ... (?)

The Travis tests have already been updated to allow testing of Python 3 in https://github.com/dokterbob/django-newsletter/tree/python3_tests. If you're doing work on this, please fork from there.

**Comment by schacki** [comment]
Hi all,
this looks like a great app and I would like to use it in a project. But it will be a Python 3 project.
Is there any plan/roadmap with regard to Python 3 support?
Thanks a lot
schacki

**Comment by dokterbob** [comment]
Hey @schacki,

We would love Python 3 support, you are more than welcome to implement it!
However, I am not currently in the need of Python 3 functionality and do not have the time to implement it pro bono.

Mathijs

**Comment by claudep** [comment]
To read about vobject Python3 status: https://github.com/adieu/vobject/issues/5

The more up-to-date version seems to be currently https://github.com/tBaxter/vobject. At least, tests start with this fork of vobject and Python 3. I would suggest switching to it.
