### ISSUE TITLE
Subscription object is not JSON serializable

### ISSUE THREAD

**Issue by amureki** [dokterbob/django-newsletter#104]
Since Django 1.6 the default session serializer uses JSON objects instead of pickle objects to circumvent potential security issues. However, the import mechanism of django-newsletter stores subscription objects which are not JSON-serializable.

## Exception
http://monosnap.com/image/OWikyTx9p7xURpTwhLNEt86M5rAnYK.png
And traceback gist: https://gist.github.com/amureki/9613750

Error rising after I choose newsletter and CSV from above and press "Upload".

## Workaround
This is due to the change in Django 1.6 session_serializer. Look here https://docs.djangoproject.com/en/1.6/ref/settings/#session-serializer 
So, if you have Django > 1.6 and django-newsletter current version, simplest way — you should add into your settings file:

    SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

## Solution
The solution would be to rewrite the import mechanism to store just the raw imported data in the session and create the subcription objects right before saving. Pull requests are much welcomed!

**Comment by martinszy** [comment]
Hi I'm using Django 1.8.1 and I got the same problem, solved the same way.

BTW: I'm using django-newsletter with cuttlefish.io as a backend to send emails and track clicks and responses, it seems to be working.

**Comment by dokterbob** [comment]
This is a pretty serious bug and it would be great to be able to solve this before the 0.6 release.

Steps:

1. Implement a test for the import code - this would be great to have anyways.
2. Setup an explicit regression test for this issue.
3. Rewrite the import mechanism to store 'raw' imported data into the session instead of the Python objects.
4. Win!
