### ISSUE TITLE
Submission delay caused possibly by timezone differences between backend and admin frontend

### ISSUE THREAD

**Issue by procmail** [dokterbob/django-newsletter#112]
Hi,

I found ticket #105 after some googling but it didn't work.

I have the latest version of django-newsletter.

My subscription is stuck in "Delayed submission" status, and there is no queue button in the submission detail view at all. There is, however, a Submit link, which I used.

However, typing on the command line:
python manage.py runjob submit 
returns immediately and there's no other message.

The submission is still there, showing "Delayed submission". What am I doing wrong?

**Comment by vaibhav-jain** [comment]
@dokterbob @procmail Can you please tell me how to resolve this issue as I am too facing the same issue. Messages stuck with delayed submission status.

```
settings.py
TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True
```

**Comment by dokterbob** [comment]
I don't think this is actually the same issue, as the above problem seemed to occur before Django's timezone support was integrated. Perhaps it's better to create a new issue describing exactly how to reproduce and then mention that it *might* be a bug/regression.

**Comment by vaibhav-jain** [comment]
Sure 
pip freeze output
```
beautifulsoup4==4.4.1
bumpversion==0.5.3
chardet==2.3.0
Django==1.8.8
django-classy-tags==0.7.1
django-debug-toolbar==1.4
django-environ==0.4.0
django-extensions==1.6.1
django-formtools==1.0
django-grappelli==2.7.3
django-imperavi==0.2.3
django-jet==0.1.3
django-mailgun==0.8.0
-e git://github.com/dokterbob/django-newsletter.git@29721ee0ad77722559a1fcbb9db10105de3162fa#egg=django_newsletter
django-reversion==1.8.7
django-sekizai==0.9.0
django-tinymce==2.2.0
django-treebeard==3.0
django-webtest==1.7.8
feedparser==5.2.1
gunicorn==19.4.5
html5lib==0.9999999
Jinja2==2.8
ldif3==3.1.1
MarkupSafe==0.23
Pillow==3.1.0
psycopg2==2.6.1
python-card-me==0.9.1
python-dateutil==2.4.0
pytz==2015.7
requests==2.9.1
six==1.10.0
sorl-thumbnail==12.3
sqlparse==0.1.18
surlex==0.2.0
unicodecsv==0.14.1
vobject==0.6.6
waitress==0.8.10
WebOb==1.5.1
WebTest==2.0.20
wheel==0.24.0
whitenoise==2.0.6
```

After submitting the message first I waited for message to be sent but then after trying 3-4 times I found that it might be a timezone issue. To test my theory I changed the publish time from my timezone (IST) to UTC
and then it worked as expected. So question is how to make it work with local timezone.
