### ISSUE TITLE
Unsubscribe page not found

### ISSUE THREAD

**Issue by procmail** [dokterbob/django-newsletter#114]
Hi,

When clicking on the email's unsubscribe link, I keep getting:
Page not found (404)
Request Method: GET
Request URL:    http://10.211.55.20:8000/newsletter/test-newsletter-2/unsubscribe/
No Newsletter matches the given query.

I have this inside urls.py:
    (r'^newsletter/', include('newsletter.urls')),

What am I doing wrong? 

After getting the above error, I tried copying the newsletter/templates/newsletter/\* to my_project/templates/, my_project/templates/newsletter/ my_project/newsletter/templates and finally my_project/newsletter/templates/newsletter/, all without avail.

**Comment by soma115** [comment]
In addition:
Usually first site existing out of the box is 'example.com'. This site corresponds to 'SITE_ID = 1' in settings.py
If you created another site without deleting 'example.com' - your new site will get 'SITE_ID = 2'
Those ID's are kept even if you delete 'example.com' later.

Add 'SITE_ID = 2' to settings.py
