### ISSUE TITLE
0.6dev 'south_migrations' Folder Causes Mass PEP8 Warnings on Test

### ISSUE THREAD

**Issue by dsanders11** [dokterbob/django-newsletter#127]
After moving old South migrations to the new 'south_migrations' folder, the PEP8 report that runs with `setup.py test` is drowned out by the fact that all of those migrations have lots of lines over 80 characters long.

It looks like django-setuptest internally excludes 'migrations' to avoid this, which is why it wasn't a problem before. After the rename that exclusion no longer stops the warnings.

There's no easy way to pass extra excludes to the PEP8 report in django-setuptest short of extending it.

Here's an interesting blog post on supporting both Django migrations and South migrations: http://treyhunner.com/2014/03/migrating-to-django-1-dot-7/

A possible fix would be to move the 'south_migrations' folder to 'migrations/south/' and use the error mechanism from the above blog post to inform users to specify the path to South migrations if necessary.

@pcraston and @dokterbob, thoughts? It'd be nice if the PEP8 report wasn't blown out, I was planning on fixing the few PEP8 issues it mentioned to get it passing clean.

**Comment by dokterbob** [comment]
@dsanders11 Essentially, very little. I'm using standard Django testing.

We'd have to set up Travis to run the tests directly (but, preferably, without a 'demo'-app) and then also to do some static and coverage analysis (with some minimal criteria, like setuptest does).

**Comment by dokterbob** [comment]
Removed django-setuptest requirement. \o/
