### ISSUE TITLE
translations

### ISSUE THREAD

**Issue by timgin** [dokterbob/django-newsletter#129]
In the README.rst it reads that the app is 100% translated to Russian, but I stumbled upon 6 empty non-translated strings in django.po, for example, the "Your subscription request was successfully received" one. Would you like me to fill those up?

**Comment by dokterbob** [comment]
Op 16 feb. 2015, om 07:48 heeft Timur Ginatullin <notifications@github.com> het volgende geschreven:

> In the README.rst it reads that the app is 100% translated to Russian, but I stumbled upon 6 empty non-translated strings in django.po, for example, the "Your subscription request was successfully received" one. Would you like me to fill those up?
Yes! Feel free to submit translations through Transifex.
https://www.transifex.com/projects/p/django-newsletter/language/ru/

I think you have to apply for membership there and then submit for membership.

Looking forward to your contribution, thanks!

Mathijs
