### ISSUE TITLE
AppRegistryNotReady("Models aren't loaded yet.") 

### ISSUE THREAD

**Issue by rodrigolins** [dokterbob/django-newsletter#130]
I'm following the installation procedure, and when I try to run the south migrations (step 8) I get this error:

File "/home/rodrigo.lins/venvs/asina-newsletter/local/lib/python2.7/site-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

My package list:
Django==1.7.6
Pillow==2.7.0
South==1.0
Unidecode==0.04.17
WebOb==1.4
WebTest==2.0.18
beautifulsoup4==4.3.2
chardet==2.3.0
django-appconf==1.0.1
django-compressor==1.4
django-debug-toolbar==1.3.0
django-extensions==1.5.1
django-imperavi==0.2.3
django-libsass==0.2
django-modelcluster==0.5
django-newsletter==0.5.2
django-redis-cache==0.13.0
django-taggit==0.12.2
django-treebeard==2.0
django-webtest==1.7.7
html5lib==0.999
libsass==0.7.0
python-dateutil==2.4.1
redis==2.10.3
requests==2.5.3
six==1.9.0
sorl-thumbnail==12.2
sqlparse==0.1.14
surlex==0.2.0
unicodecsv==0.11.0
vobject==0.6.6
wagtail==0.8.3
waitress==0.8.9

Does anyone knows if it is a bug or not?

**Comment by pcraston** [comment]
0.5.2 hasn't got support for Django 1.7. Try installing the source from the latest master branch, that uses Django migrations.

(also you probably shouldn't have South and Django 1.7 in your package list)

**Comment by dokterbob** [comment]
@pcraston Maybe we should roll out a 0.6 release. What do you reckon'?

**Comment by pawelByszewski** [comment]
Guys I have the same problem thus +1 for 1.7 support

**Comment by pcraston** [comment]
@dokterbob Sounds good to me. So 0.6 would be created from latest master to add 1.7 support? 
I'm trying to remember, the latest master works ok with older versions too (tests are passing), so it should be fine to have one release for all?

**Comment by dokterbob** [comment]
Yes, one release for them all from current master. If you�re unsure it works for every Django version, we might opt for a prerelease so people can give feedback.

However, given that Django support has been in master for quite a while and so far no one has reported bugs with Django versions - perhaps we should just make a go at it. The only place where I think issues might be expected is schema migrations.

Stuff to do before the release: (mostly note to self)
[ ] Update tests to have some idea of what happends for Django 1.8
[ ] Check status on (open) issues. Can they be closed? Do they have acceptable pull req�s?
[ ] Pull in translations.
[ ] Update CHANGES.txt
[ ] Create package
[ ] Distribute with pip

Perhaps we should do this one together, i.e. reserve a couple of hours some time some day. What part of the world are you in? (Timezone-wise)

**Comment by pcraston** [comment]
I've just been updating our project that uses django-newsletter to django 1.8 and there are some issues with django-newsletter and django 1.8.
I'll take a look at this in the next few days.

I'm in London, you in Amsterdam?

**Comment by dokterbob** [comment]
At the moment. In any case, in Europe. :)

Would be great to have the issues filed in GH at least - so people know they�re there.

If you feel like it we could do a sprint next week to close outstanding issues and do a release the same day. I think a new release which does not support 1.8 would be a bit of a pity.

**Comment by pcraston** [comment]
Yes, I agree. Will take a look at what issues there are and how easy they are to fix.

**Comment by pcraston** [comment]
Had a quick look at the only obvious issue (apart from deprecation messages) seems to be the depreciation of IPAddressField for GenericIPAddressField. That gets added to the Django System check Warning, which obviously doesn't look good.

Any idea how we can upgrade to GenericIPAddressField while still maintaining compatilibility with old Django versions?

**Comment by dokterbob** [comment]
According to Django�s deprecation policy we can expect it to be removed by the time Django drop�s support for releases with the legacy field - which is when we switch from the IPAddressField to the GenericIPAddressField. Hence in that case we would simply update the code and leave the warnings there in the meantime.

Alternately, we could attempt an import of the generic field as a constant. If this yields an error, fall back to the legacy one instead. Something like this:

    try:
        from blabla import GenericIPAddressField as IP_ADDRESS_FIELD
    except ImportError:
        from blabla import IPAddressField as IP_ADDRESS_FIELD


    class FunkyModel(models.Model):
        something = IP_ADDRESS_FIELD()

**Comment by pcraston** [comment]
Created a PR with what I think is required to fix Django 1.8 issues.
But it looks like the tests won't work with Django 1.8 as django-setuptest doesn't support 1.8 -> https://github.com/praekelt/django-setuptest/issues/23

**Comment by dokterbob** [comment]
This is part of 1.8 support #131
