### ISSUE TITLE
'SubmissionAdmin' object has no attribute 'queryset'

### ISSUE THREAD

**Issue by fpghost** [dokterbob/django-newsletter#133]
I'm testing the commit `git://github.com/dokterbob/django-newsletter.git@8f58a8b38e27227972f8b9f9d61627be40f677bd` as I need to use with Django1.8.

When adding a new submission in the admin, then clicking `Submit` button for that submission, I get the following

    Traceback:
    File "/srv/transmezz/venv/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
    132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
    File "/srv/transmezz/venv/lib/python2.7/site-packages/newsletter/admin_utils.py" in wrapper
    37.             return self.admin_site.admin_view(view)(*args, **kwargs)
    File "/srv/transmezz/venv/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapped_view
    110.                     response = view_func(request, *args, **kwargs)
    File "/srv/transmezz/venv/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
    57.         response = view_func(request, *args, **kwargs)
    File "/srv/transmezz/venv/lib/python2.7/site-packages/django/contrib/admin/sites.py" in inner
    233.             return view(request, *args, **kwargs)
    File "/srv/transmezz/venv/lib/python2.7/site-packages/newsletter/admin.py" in submit
    144.         submission = self._getobj(request, object_id)
    File "/srv/transmezz/venv/lib/python2.7/site-packages/newsletter/admin_utils.py" in _getobj
    15.                 obj = self.queryset(request).get(pk=unquote(object_id))

    Exception Type: AttributeError at /en/admin/newsletter/submission/1/submit/
    Exception Value: 'SubmissionAdmin' object has no attribute 'queryset'

Obviously it's related to the `submit` view of the `SubmissionAdmin` model in `admin.py`. There is the line `submission = self._getobj(request, object_id)` in this view, which uses `_getobj` of the `ExtendibleModelAdminMixin` mixin of `admin_utils.py`, which is the thing that calls `queryset` method on the `SubmissionAdmin` model: 

    obj = self.queryset(request).get(pk=unquote(object_id))

Could anyone shed light on the matter? It appears in previous versions of django `admin.ModelAdmin` did have the queryset method, but not in 1.8?

**Comment by fpghost** [comment]
Looks like this would explain it: https://docs.djangoproject.com/en/1.6/releases/1.6/#get-query-set-and-similar-methods-renamed-to-get-queryset

**Comment by pcraston** [comment]
Can you replace queryset with get_queryset?

I already did that in a few places in my PR but must have missed this one.

**Comment by fpghost** [comment]
Sent a pull request.

**Comment by pcraston** [comment]
Cool thanks. Just on holiday, will check it out when I get back.

**Comment by dokterbob** [comment]
Hey @fpghost ,@pcraston,

Could you inform me on the status of this one? I am considering shipping the 0.6 release with 1.8 support feel that perhaps we should have this in - but I can't seem to find the related pull request (tip: next time refer to the issue number #<number> to automagically link them.

Cheers!
M

**Comment by pcraston** [comment]
This was included in my recent pull request. You can close this one.

**Comment by dokterbob** [comment]
\o/
