### ISSUE TITLE
Bounce Detection and Handling

### ISSUE THREAD

**Issue by COLABORATI** [dokterbob/django-newsletter#137]
Seriously, a newsletter software really needs bounce detection and bounce handling and should not be published if it does not have this feature implemented. I do not see this mentioned anywhere, is this really missing? If it is missing, then please let this be the feature request for this basic requirement.

**Comment by dokterbob** [comment]
Hey Colaborati,

Thanks for the feedback. If you would like this feature, please feel free to implement it. I'm sure many users would be very thankful about it.

Besides this, before filing issues, please take the effort to look for existing tickets covering the same feature scope, such as #9 and #89. Getting this information is not trivial, as the actual mail submission is done through an external SMTP server - typically a mail submission service like Sendgrid.

Closing this ticket as a dup.

M
