### ISSUE TITLE
Refactor addressimport tests

### ISSUE THREAD

**Issue by dokterbob** [dokterbob/django-newsletter#140]
There is test code living in `addressimport/test_*.py` which should live in the `tests` folder and actually be run. Apart from improving the code this would prevent the tests from being counted as uncovered.

**Comment by claudep** [comment]
It would be nice if you could provide the data files which I didn't find in the repo.

**Comment by dokterbob** [comment]
This was private data from my personal address book which I had foolishly committed to the repository and have subsequently purged from history. I am sorry, but I do not have a backup of them.

I suppose the best would be to just create some test data yourself. Previously, I used Apple's iCal to generate vCards and Mozilla's Thunderbird for LDIF's.
