### ISSUE TITLE
updates for django 1.8

### ISSUE THREAD

**Issue by welworx** [dokterbob/django-newsletter#143]
hey,

to get django-newsletter work with django 1.8.3 I had to change the following:

the changed parts are marked with comments:

models.py:

    .....
    
    from django.conf import settings
    
    from sorl.thumbnail import ImageField
    
    from .utils import (
        make_activation_code, get_default_sites, ACTIONS, get_user_model
    )
    
    from django.conf import settings #### add this
    
    #User = get_user_model() #### remove this line
    
    
    .................
    
    
    class Subscription(models.Model):
        user = models.ForeignKey(
            settings.AUTH_USER_MODEL, blank=True, null=True, verbose_name=_('user')
        ) ### replace User with settings.AUTH_USER_MODEL
    
        name_field = models.CharField(
            db_column='name', max_length=30, blank=True, null=True,
            verbose_name=_('name'), help_text=_('optional')
        )
    
        ....................

admin_utils.py:

    ...
    import django # added
    
    class ExtendibleModelAdminMixin(object):
       ...
    
        def _view_name(self, name):
    
            if django.VERSION < (1, 8):
                model_name = self.model._meta.module_name
            else:
                model_name = self.model._meta.model_name
    
            return '%s_%s_%s' % (self.model._meta.app_label, model_name, name)
    
            #info = self.model._meta.app_label, self.model._meta.module_name, name
            #return '%s_%s_%s' % info

admin_forms.py:

    add fields='__all__' to Meta class from SubscriptionAdminForm and SubmissionAdminForm

would be nice if it could be implemented.

**Comment by dokterbob** [comment]
Hey, 

Did you try this on master? It should support 1.8 pretty much from the start. 

M

welworx <notifications@github.com> schreef op 10 augustus 2015 21:52:03 CEST:
>hey,
>
>to get django-newsletter work with django 1.8.3 I had to change the
>following:
>
>the changed parts are marked with comments:
>
>models.py:
>
>    .....
>    
>    from django.conf import settings
>    
>    from sorl.thumbnail import ImageField
>    
>    from .utils import (
>       make_activation_code, get_default_sites, ACTIONS, get_user_model
>    )
>    
>    from django.conf import settings #### add this
>    
>    #User = get_user_model() #### remove this line
>    
>    
>    .................
>    
>    
>    class Subscription(models.Model):
>        user = models.ForeignKey(
>settings.AUTH_USER_MODEL, blank=True, null=True, verbose_name=_('user')
>        ) ### replace User with settings.AUTH_USER_MODEL
>    
>        name_field = models.CharField(
>            db_column='name', max_length=30, blank=True, null=True,
>            verbose_name=_('name'), help_text=_('optional')
>        )
>    
>        ....................
>
>
>admin_utils.py:
>
>    ...
>    import django # added
>    
>    class ExtendibleModelAdminMixin(object):
>       ...
>    
>        def _view_name(self, name):
>    
>            if django.VERSION < (1, 8):
>                model_name = self.model._meta.module_name
>            else:
>                model_name = self.model._meta.model_name
>    
>     return '%s_%s_%s' % (self.model._meta.app_label, model_name, name)
>    
> #info = self.model._meta.app_label, self.model._meta.module_name, name
>            #return '%s_%s_%s' % info
>
>
>admin_forms.py:
>
>add fields='__all__' to Meta class from SubscriptionAdminForm and
>SubmissionAdminForm
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/dokterbob/django-newsletter/issues/143

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by welworx** [comment]
hey,

i have installed the pip version (0.5.2) and it did not work.

**Comment by dokterbob** [comment]
It works *fine* with Django 1.5. Please RTFM, on the PIP page and check the supported versions.

The 0.6 is about to be released but there are two more issues to be fixed before shipping it out. 0.6 will support all the latest Django versions.

If you would like to run ahead of this, install the latest development straight from GIT with:

`pip install -e git+https://github.com/dokterbob/django-newsletter.git#egg=django-newsletter`
