### ISSUE TITLE
On latest Django version, ```manage.py migrate``` complains about "Your models have changes that are not yet reflected in a migration”

### ISSUE THREAD

**Issue by pcraston** [dokterbob/django-newsletter#144]
This is because migrations were created using the lowest django version supported (as per https://docs.djangoproject.com/en/1.8/topics/migrations/#supporting-multiple-django-versions).

If you run ```manage.py makemigrations``` (on latest Django version) it creates a new migration with following changes:

```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.db.models.manager
import django.contrib.sites.managers


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20150416_1555'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='newsletter',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='ip',
            field=models.GenericIPAddressField(null=True, verbose_name='IP address', blank=True),
        ),
    ]
```

We can't add this migration, as it will break for Django < 1.8. Any ideas on how to fix this welcome!

**Comment by dokterbob** [comment]
@pcraston I'll have to think about this one. Do you think it should be blocking the upcoming release?

**Comment by pcraston** [comment]
@dokterbob I'm not sure. It's rather annoying but then there doesn't seem to be a clear consensus in the Django community on how to deal with this situation. Surely, other apps that support multiple Django versions must have the same problem?

Do you think the "CurrentSiteManager" custom ModelManager could be removed and replaced by some other functionality?

With regards to the IPAddressField, I'm not sure how to deal with that one.

**Comment by dokterbob** [comment]
So I looked a bit into this. As it seems, this is not currently breaking the app both for new as well as for existing users.

Just for clarity, let me see if I understand the situation properly: the `GenericIPAddressField` does not exist < 1.8, hence we cannot make a migration containing it. As [support](https://www.djangoproject.com/download/#supported-versions) for 1.4 LTS is ending in October and that for 1.7 is ending in December, my suggestion would be just to wait until we can drop support for older versions.

With regarding to the manager: I have no idea why this suddenly appears here as this manager was there all along. Is this a Django 1.8 thing?

**Comment by dokterbob** [comment]
For now, I'm assuming we can leave this for the upcoming release.

**Comment by pcraston** [comment]
Yes, Django 1.8 started capturing modelmanager information in migrations.
But you're right, the master branch works fine with the latest Django release and it's a minor issue which will be resolved when django-newsletter stops supporting 1.4.
So I think it makes sense to put the release out but leave this ticket open to let people know that we're aware of the migrations issue. 
(We've been using the latest master branch with the latest Django version for months now and it works without problems)

**Comment by dokterbob** [comment]
Alright.

Meanwhile, I am working on #108, which requires quite a big refactoring but will yield a big security improvement, before releasing 0.6.

**Comment by dokterbob** [comment]
@pcraston We've dropped support for 1.4 some time ago, can this one be closed? (If so, feel free to go ahead! :))

**Comment by pcraston** [comment]
Sounds good! Closing this now.
