### ISSUE TITLE
Submission admin always takes last message

### ISSUE THREAD

**Issue by gabn88** [dokterbob/django-newsletter#170]
Unless you take the flow with the right upper button, it seems like a submission always take the last message.

## Confirmed steps for reproduction 
1. Create two messages belonging to same newsletter, marking one explicitly as last
2. Create new submission from Newsletter admin (not from Message preview)
3. Select the newsletter first added
4. Click 'save and edit'

## Expected result
Change form shows last newsletter

## Found result
Last added newsletter is selected.

**Comment by dokterbob** [comment]
Possibly related to #171

**Comment by dokterbob** [comment]
When saving again, the value is preserved.

**Comment by dokterbob** [comment]
I still don't know what the cause is, however, the following factors are **NOT** causing it:
* The custom `SubmissionAdminForm`.
* The custom `change_form.html` template.
* The `ExtensibleModelAdmin` base class.

At this point I am quite clueless as to what might be the cause of this.

**Comment by dokterbob** [comment]
I've written a regression test but no clue as to the solution. Feel free to pick this one up at any time (but make sure to notify me so we won't accidentily do double work).

**Comment by claudep** [comment]
I think the culprit is the `Sumission.save()` method:
```
if self.pk is None:
            self.message = Message.get_default()
```
I think the intent was maybe to test `if not self.message`?

**Comment by dokterbob** [comment]
@claudep Thanks, that's obviously it. 

I guess when I wrote it I wanted to give `Submission` a sensible default. Hence it *should have* been `if not self.message`. However, by now (several years later) it is obvious this should end up as a default value for the form.

Ref: https://docs.djangoproject.com/en/1.9/ref/forms/fields/#initial

**Comment by gabn88** [comment]
Great that this is resolved so fast! This is why I <3 the Django community!
