### ISSUE TITLE
get_user_model raises error Models aren't loaded yet.

### ISSUE THREAD

**Issue by sonus21** [dokterbob/django-newsletter#175]
I am testing django-nesletter in my project it keeps throwing error.
Settings file:
```python
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#ml3n#s&f2pe73w9m*f!ifnt-ec7jya2-om5247rol)xm^^&k='
DEBUG = True
ALLOWED_HOSTS = []
AUTH_USER_MODEL = 'auth.User'
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_extensions',
    'sorl.thumbnail',
    "newsletter",
)
MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)
ROOT_URLCONF = 'foo.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'foo.wsgi.application'
#Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True
STATIC_URL = '/static/'
```

Even when AUTH_USER_MODEL is removed from settings file it through error. 

##Python 2.7
##Django: 1.8.6

**Comment by claudep** [comment]
Please provide the full traceback.

**Comment by sonus21** [comment]
projects/web/env/bin/python2.7 projects/nano/manage.py runserver 127.0.0.1:8000
projects/web/env/local/lib/python2.7/site-packages/django/db/utils.py:239: RemovedInDjango19Warning: In Django 1.9 the TEST_COLLATION connection setting will be moved to a COLLATION entry in the TEST setting
  self.prepare_test_settings(alias)
projects/web/env/local/lib/python2.7/site-packages/django/db/utils.py:239: RemovedInDjango19Warning: In Django 1.9 the TEST_COLLATION connection setting will be moved to a COLLATION entry in the TEST setting
  self.prepare_test_settings(alias)
Unhandled exception in thread started by <function wrapper at 0x7f1bd6880d70>
Traceback (most recent call last):
  File "projects/web/env/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "projects/web/env/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 107, in inner_run
    autoreload.raise_last_exception()
  File "projects/web/env/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 252, in raise_last_exception
    six.reraise(*_exception)
  File "projects/web/env/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "projects/web/env/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "projects/web/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "projects/web/env/local/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "projects/web/env/local/lib/python2.7/site-packages/newsletter/models.py", line 29, in <module>
    User = get_user_model()
  File "projects/web/env/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 150, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL)
  File "projects/web/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "projects/web/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

**Comment by claudep** [comment]
Great. Could you please try again with `python manage.py runserver --noreload` to see if the traceback is the same?

**Comment by dokterbob** [comment]
@sonus21 Are you installing from `master` or from PyPI? The PyPI version is pretty outdated and I remember people complainging about `AppRegistryNotReady` errors some time ago.

**Comment by sonus21** [comment]
@dokterbob From PyPI 
@claudep Same traceback

**Comment by dokterbob** [comment]
@sonus21 The PyPI version only supports up to Django 1.5. Please install the GH version as per the instructions in the docs.
