### ISSUE TITLE
Set default subscription for new user.

### ISSUE THREAD

**Issue by sonus21** [dokterbob/django-newsletter#176]
Is there any simple way to configure such that when a user signup, they will added to subscription list.

**Comment by dokterbob** [comment]
You'll have to wire it into whatever you're using to have users signup. For example, connect it to something like django-registration (I've done this myself a couple of times).

**Comment by dokterbob** [comment]
By the way, I am sure it would be a great help if you could document on this process.

Protip: connect to the [`user_registrated`](https://django-registration.readthedocs.org/en/v0.8/signals.html#registration.signals.user_registered) signal of `django-registration`.

**Comment by sonus21** [comment]
where should I document this process, I will be using django internal authorization model User for this?

**Comment by dokterbob** [comment]
Maybe first set up registration and then see how you can hook it up to this package.

Documentation goes into the Sphinx docs in the repo and will be rendered to Read The Docs.
