### ISSUE TITLE
Use premailer for HTML

### ISSUE THREAD

**Issue by gabn88** [dokterbob/django-newsletter#178]
I'm using the app now and it works great! 

However, I would like to use a [Premailer](https://pypi.python.org/pypi/premailer), because my mail shows up in the wrong format on some devices. Is this possible and has anyone done this before?

**Comment by dokterbob** [comment]
Obviously, this is possible. However, I have not seen it implemented yet.

Would be a very worthwhile feature though, although perhaps this is more something to do manually once when creating the templates?

**Comment by gabn88** [comment]
Well, that is of course also a good option! But the problem in my case was that the preview was incorrect. I had a * {font-family: "Helvetica Neue" arial etc} that got overwritten in many mail programs. I have manually fixed it now, but I think running a premailer before the preview would also solve this?

**Comment by dokterbob** [comment]
Thought about it for a bit. I guess this could be implemented but I am a bit afraid of adding another (hard) dependency.

I've noticed in the code that there are actually two places where templates are rendered. It would be good to abstract this out to having a single place (i.e. the templates model) and then providing a configuration option to enable premailer.

If you provide a patch, make sure to provide a basic test and documentation as well. Thanks!

**Comment by Sheepzez** [comment]
@dokterbob Is it possible to do this currently? I'm using Python premailer in conjunction with another django-app (comments system), is there any way to integrate it in the current version of django-newsletter?

**Comment by dokterbob** [comment]
I guess the most sensible way to do this is just to use template tags. Have not looked at the code but might Djang- premailer not be up to the job? 

In that case it might be worth hinting at it from the docs.

**Comment by Sheepzez** [comment]
@dokterbob Thanks for the suggestion! I've got it working well using django-premailer. Also lets me have all the emails for my site inherit from the same base, which is nice.

**Comment by dokterbob** [comment]
Thanks for the feedback!

It would be great if you could find some time to write something about this in the documentation, I’m sure many users would appreciate!

**Comment by Sheepzez** [comment]
@dokterbob I'll PR an example in the docs sometime in the next couple days :)

**Comment by dokterbob** [comment]
Great, thanks!

**Comment by Sheepzez** [comment]
@dokterbob You mentioned earlier up that you were thinking about having/not having this as part of django-newsletter, and being enabled by a config setting. Did you have any more thoughts on what you would regard as the best solution?

Options seem to be to have it as part of django-newsletter, or just indicate that people use an app such as django-premailer.

**Comment by dokterbob** [comment]
As it is perfectly doable to have this functionality without integrating it explicitly, I'd prefer just documenting this as an optional approach, as @Sheepzez has done in #191.

**Comment by gabn88** [comment]
Wow, thanks! Never imagined it would be so easy to integrate it!! Thank you!

**Comment by dokterbob** [comment]
@woodz- Maybe create a new ticket specifically addressing the issues you're experiencing, and then referring the one here. That way, others are better able to find it.
