### ISSUE TITLE
German translation: remaining last string

### ISSUE THREAD

**Issue by WGierke** [dokterbob/django-newsletter#180]
It seems like there is only one string remaining that should be translated to German.
I tried to translate it using the transifex online tool but there were issues while connecting to the server.

However, the translation is:
File extension '%s' was not recognized.
->
Die Dateiendung '%s' wurde nicht erkannt.

Cool project, keep it up! :+1: :)

**Comment by dokterbob** [comment]
Just saw your request for language de_DE, which I denied. I would welcome your contribution to ‘de’ though. I’ve manually added your string but it would be great to welcome you to the German team anyways, for future versions. But I guess that’s a thing between you and the team manager for German.
