### ISSUE TITLE
python 3 compatibility

### ISSUE THREAD

**Issue by robert-kisteleki** [dokterbob/django-newsletter#182]
The docs claim python 3 (specifically, 3.4) compatibility, but I bumped into this while trying to install and do "manage migrate":

==
...
  File "/home/me/python3/lib/python3.4/site-packages/newsletter/models.py", line 597
    except Exception, e:
                    ^
SyntaxError: invalid syntax
==

Granted, the source says "TODO: Test coverage for this branch" but still :-)

**Comment by claudep** [comment]
This is fixed in master (https://github.com/dokterbob/django-newsletter/blob/master/newsletter/models.py#L613). However no release has been done yet with the Python 3 support, you should install from Git master to take advantage of the Python 3 support.

**Comment by robert-kisteleki** [comment]
Fair enough. However, since the changes file has not been updated for two years, it's pretty difficult to find this info for myself ;-)

I'm fighting with "django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet." now, a typical django 1.9 issue, perhaps that's also been solved since the last release?

**Comment by claudep** [comment]
@dokterbob I know you'd like to fix #108 before a new release, but I think a release would still be nice.

**Comment by dokterbob** [comment]
I think your right. The main thing now is to compose a changelog from the last version and a clearly documented upgrade path from South (this gave some weird problems when I recently upgraded a site). 

Feel free to create issues for the above (they're already on my todo but you're welcome to pick them up as well.)
