### ISSUE TITLE
Document upgrade steps from 0.6

### ISSUE THREAD

**Issue by dokterbob** [dokterbob/django-newsletter#185]
As far as I'm concerned this is the only issue blocking the 0.6 release.

The only thing I am aware of is that going from South migrations to Django migrations does not go as smoothly as it should. Though I haven't been able to consistently reproduce it.

Perhaps anyone is able to provide me with input on this one?

**Comment by claudep** [comment]
I have no installation to test with, but based on https://docs.djangoproject.com/en/1.9/topics/migrations/#upgrading-from-south, the procedure should be:
- remove `'south'` from INSTALLED_APPS
- run `python manage.py migrate --fake-initial`

If anyone faces errors during these simple steps, please report them so we can investigate.

**Comment by sergei-maertens** [comment]
I might be able to test it on an installation before I leave for vacation

**Comment by dokterbob** [comment]
I did face errors - but was too busy fixing other issues to be able to afford the time to dig into it (plus it might be setup-dependent). However, I will be migrating the same setup again in a few weeks as I update production.

**Comment by claudep** [comment]
Congrats for the release \o/

**Comment by dokterbob** [comment]
Wow that's fast. You needed it badly didn't you? ;)

Glad to have finally shipped this out (though not fixing the security issue is still a bit of a sting).
