### ISSUE TITLE
Move test requirements to requirements_test.txt

### ISSUE THREAD

**Issue by dokterbob** [dokterbob/django-newsletter#190]
Currently, webtest and django-webtest are present in the [normal requirements](https://github.com/dokterbob/django-newsletter/blob/master/requirements.txt#L11) because, by default, Django used to run tests for all pluggable apps. However, I do not think this is currently still the case and perhaps these should be moved.

@claudep What do you think about it?

**Comment by claudep** [comment]
I'm not familiar with webtest. If we can replace self.app with self.client with no harm, then one less requirement is always better.

**Comment by claudep** [comment]
Oh, your question was about moving, not removing. So the answer is "sure", of course.
