### ISSUE TITLE
Need help figuring out serving Images

### ISSUE THREAD

**Issue by agelinas** [dokterbob/django-newsletter#196]
I like django-newsletter but am having trouble figuring out why it is not finding the images when I click on display in Message form.

The image files upload correctly to _newsletter/images_ and the _image_ field is updated with the path for the image, but the image is not displayed in the preview'.

I read most of the code, but am not a coder. I saw that MEDIA_URL is used in the context and don't know if it needs to be set in settings.py or if some other settings need to be changed or added.

**When I click on a picture thumbnail inside an article (optional image):**

```
[06/Mar/2016 16:24:11] "GET /admin/newsletter/message/1/change/newsletter/images/2016/03/06/3083728_oz4RiPN.jpg/ HTTP/1.1" 302 0
Not Found: /admin/newsletter/message/1/change/newsletter/images/2016/03/06/3083728_oz4RiPN.jpg/change/
[06/Mar/2016 16:24:11] "GET /admin/newsletter/message/1/change/newsletter/images/2016/03/06/3083728_oz4RiPN.jpg/change/ HTTP/1.1" 404 11488
```

**When I click on the _Preview_ button:**

```
[06/Mar/2016 16:32:36] "GET /admin/newsletter/message/1/preview/ HTTP/1.1" 200 11140
/home/alain/django/venv/django_env/lib/python3.4/site-packages/newsletter/admin.py:278: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
  return HttpResponse(html_template.render(c))

/home/alain/django/venv/django_env/lib/python3.4/site-packages/newsletter/admin.py:296: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
  return HttpResponse(text_template.render(c), content_type='text/plain')

[06/Mar/2016 16:32:36] "GET /admin/newsletter/message/1/preview/text/ HTTP/1.1" 200 431
[06/Mar/2016 16:32:36] "GET /admin/newsletter/message/1/preview/html/ HTTP/1.1" 200 10851
```

**Installed packages:**
Django==1.9.2
ExifRead==2.1.2
Pillow==3.1.1
PyJWT==1.4.0
Unidecode==0.04.19
WebOb==1.5.1
WebTest==2.0.20
argparse==1.1
beautifulsoup4==4.4.1
braintree==3.25.0
cffi==1.5.2
chardet==2.3.0
cryptography==1.2.3
django-annoying==0.8.7
django-bootstrap3==6.2.2
django-bower==5.1.0
django-braces==1.8.1
django-crispy-forms==1.6.0
django-debug-toolbar==1.4
django-extensions==1.6.1
django-filter==0.12.0
django-localflavor==1.2
django-mptt==0.8.1
django-newsletter==0.6
django-payments==0.9.2
django-polymorphic==0.8.1
django-registration-redux==1.4
django-sortedm2m==1.1.1
django-tables2==1.1.2
django-tinymce==2.2.0
django-webtest==1.7.8
easy-thumbnails==2.3
future==0.15.2
icalendar==3.9.2
idna==2.0
ldif3==3.1.1
psycopg2==2.6.1
pyasn1==0.1.9
pycparser==2.14
python-card-me==0.9.3
python-dateutil==2.4.2
pytz==2015.7
requests==2.9.1
six==1.10.0
sorl-thumbnail==12.4a1
sqlparse==0.1.18
stripe==1.30.0
suds-jurko==0.6
surlex==0.2.0
unicodecsv==0.14.1
waitress==0.8.10
xmltodict==0.10.1

**Thank you,**

Alain

**Comment by dokterbob** [comment]
You need to include the full absolute URL (e.g. starting with `http(s)`) to be able to link to the web as within emails there are no absolute URL's (the email client has no idea and doesn't care which site an email was sent from).

Alternately, you might set `MEDIA_URL` to a full absolute address (e.g. `http://<my_domain>/static/media/`).

If you feel this is really confusing to novice users, you are welcomed to fork and [make a pull request](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) for an addition in the documentation.
