### ISSUE TITLE
config DELAY_BETWEEN_EACH_EMAIL

### ISSUE THREAD

**Issue by mullerivan** [dokterbob/django-newsletter#198]
to skip spam is nice to have some delay between each email :)

**Comment by mullerivan** [comment]
my approximation

https://github.com/mullerivan/django-newsletter/commit/49de37e5c41be8596b0298d8dbe3829d2a722e85

**Comment by mullerivan** [comment]
#201

**Comment by dokterbob** [comment]
@mullerivan Wait,
