### ISSUE TITLE
subscribe from home page

### ISSUE THREAD

**Issue by andreav** [dokterbob/django-newsletter#215]
Hi, 
I'm wondering how to integrate the form in another page (like #84 but I'm developing templates and views, and I have ajax on site).

My use case is to let a user subscribe the main newsletter from the home page.
The user can be logged or not (anonymous).

If possible (but optional), after entering the email and clicking "subscribe" I would prefer to let the user stay on the main page (no redirections), and show just a popup informing a successful subscription.

Can you tell me main steps to obtain this?

Thank you.

**Comment by andreav** [comment]
So far:
- inside my home page view I'm creating a SubscribeRequestForm(newsletter=nl)
- I render it in the template
- OK: the subscription happens!
- KO: there is still a redirect to "subscribe activate" page (not critical)

Is this way of using SubscribeRequestForm from a function view allowed/correct?
Do you know a way to avoid redirect? 

Here the code:

```
 def home(request):
    ...
    nl = Newsletter.objects.get(slug='example')
    subscribe_form = SubscribeRequestForm(None, newsletter=nl)
```
Then into template:
```
    <form enctype="multipart/form-data" method="post" action="/newsletter/example/subscribe/confirm/">
        {% csrf_token %}
        {{ subscribe_newsletter_form }}
        <p><input id="id_submit" name="submit" value="Subscribe" type="submit"></p>
    </form>
```

SubscribeRequestView seems to access also self.request.META.get('REMOTE_ADDR')
How can I pass request to it?
If I try this:

    subscribe_form = SubscribeRequestForm(request, newsletter=nl)

I get an error while rendering the form:

    'WSGIRequest' object has no attribute 'get'

I will continue investigating.
Thank you for any help.

**Comment by andreav** [comment]
Ok, no more redirect now!
I manage the submit through JQuery like this (ref - http://stackoverflow.com/questions/25983603/how-to-submit-html-form-without-redirection)

    jQuery(document).ready(function($){
        $("form#subscribe-nl span").click(function() {
            var url=$(this).closest('form').attr('action'),
            data=$(this).closest('form').serialize();
            $.ajax({
                url:url,
                type:'post',
                data:data,
                success:function(){
                    //whatever you wanna do after the form is successfully submitted
                }
            });
        });
    });

Still remains the questions about self.request.META.get('REMOTE_ADDR'),

**Comment by mohibJV** [comment]
@andreav I'm trying to do something similar in Django CMS. Can get the form to appear after registering a plugin with a render_template pointed to the 'subscription_subscribe.html' template. Doesn't seem to want to create a record in subscriptions though. Any thoughts?

**Comment by andreav** [comment]
Sorry, I do not know Django CMS very well.
Are you able to create a subscription with the standard app page (^<newsletter_slug:s>/subscribe/confirm/$)?

**Comment by mohibJV** [comment]
No problem. I managed to get it working by creating a cms plugin with the form (subclassed it to remove the name field). Just need to deal with the redirect now.

**Comment by dokterbob** [comment]
@mohibJV Very useful contrib. I can confirm that using an AJAX request is the way to go.

It would be great to have this documented though I've created a separate ticket #240 for documenting this. Would be great if you could manage to write this down for other users to work with.
