### ISSUE TITLE
Need help with sending emails

### ISSUE THREAD

**Issue by mihirsevak** [dokterbob/django-newsletter#219]
I am new to this app and I followed entire documentation but I am not able to send emails automatically. I have my Email configurations correctly set in settings file because I wrote a function to test those settings and that function is sending emails well. I am using gmail account to send emails but when I am doing "./manage runjob submit" I don't see any output nor emails are sent to the subscribers. 

Can someone help me out?
Thanks.

**Comment by dokterbob** [comment]
Did you try running it with -v? 

It’s probably just something you’ve overread in the documentation.

**Comment by mihirsevak** [comment]
Thanks. Finally I got it working. I was using gmail in my settings file and sender as someone from my website so it was going to spam folder. 

That leads to another question. Is there any way I can have multiple settings for multiple newsletters?? And depending on which newsletter is being sent it picks up right settings?? Is that a possibility???

Thanks.

**Comment by dokterbob** [comment]
If you implement it, it's possible. Good luck!

**Comment by dmarcelino** [comment]
@dokterbob, I've followed the [Installation docs](http://django-newsletter.readthedocs.io/en/latest/installation.html) and `./manage.py runjob submit` doesn't seem to be working for me.

I also tried `./manage.py runjob newsletter submit -v 3` and the only output was `Executing job: submit (app: newsletter)` and nothing else. In http://127.0.0.1:8000/admin/newsletter/submission/ I still see my `Submission` stating status "Not sent.". Tried this on 2 machines with no luck.

Can you point me out to where I should be looking to find the problem? Any tips are welcomed, thanks!

**Comment by dokterbob** [comment]
You have to go to the detail view of the submission and click submit to put it in the state ‘Submitting’.

**Comment by dmarcelino** [comment]
Feeling slightly embarrassed... 😊 Not sure how I missed that. That did the trick, thanks!

**Comment by dokterbob** [comment]
No problem on your side. It’s a usability issue that needed fixing since django-newsletter was developed. Any contributions are greatly appreciated.

**Comment by fauziame** [comment]
Hi there, I have a problem here, the state of the newsletter is submitting and then I tried ./manage.py runjob newsletter submit -v 3 it showed Executing job: submit (app: newsletter) but i still didn't receive anything to my email. I also applied django email settings, yet nothing!

What am I missing here?
