### ISSUE TITLE
'Dear None' when name field is empty

### ISSUE THREAD

**Issue by claudep** [dokterbob/django-newsletter#221]
The name field of a subscription can be left empty. When it's the case, the subscribe/unsubscribe messages start with an unfortunate "Dear None," line.
Should we add a `name_or_email` method to `Subscription`, or add a new `name` variable to the message contexts?

**Comment by dokterbob** [comment]
I'd prefer changing the default templates to follow the `{% if name %}{{ name }}{% endif %}` pattern.

**Comment by claudep** [comment]
So in that case, `{% if name %}{{ name }}{% else %}{{ email }}{% endif %}`, or just have a simple `Dear,`? Is it acceptable English?

**Comment by dokterbob** [comment]
In email, it seems to be. However, if we want to be properly formal, we could always use "Dear Sir/Madam”

**Comment by dimitrisr** [comment]
Instead of `{% if name %}{{ name }}{% else %}{{ email }}{% endif %}` maybe `{%firstof name "Sir/Madam" %}`

**Comment by dokterbob** [comment]
@claudep I'm all for going with @dimitrisr's suggestion. Pull request much welcomed. :)

**Comment by adi-** [comment]
I guess `{{ name|default:"Sir/Madam" }}` is easier to read.

**Comment by dokterbob** [comment]
@adi- LGTM. PR welcome! :)

**Comment by aquilesC** [comment]
I've made a PR: #290 
Hope it helps!

**Comment by dokterbob** [comment]
:(

It seems the `|default:` doesn't sit well with `msgfmt`- you can't actually use string literals in a blocktrans block.. Anyways, I'm fixing it now.
