### ISSUE TITLE
message saves to the wrong newsletter

### ISSUE THREAD

**Issue by newearthmartin** [dokterbob/django-newsletter#224]
When in the django admin you create a new message and select a newsletter, and save, the message gets associated with another newsletter. The you need to change the newsletter again, and then it saves correctly.

**Comment by dokterbob** [comment]
@newearthmartin Could you (or anyone) confirm this issue (from current master)?

**Comment by newearthmartin** [comment]
Yes, it is still happening:

This is the message before saving, with newsletter "Active users" :

<img width="773" alt="screen shot 2017-11-17 at 11 59 43" src="https://user-images.githubusercontent.com/1507266/32953429-ec706766-cb8e-11e7-86f9-b73cf496b8d0.png">

This is after saving, with newsletter "All users":

<img width="772" alt="screen shot 2017-11-17 at 11 59 54" src="https://user-images.githubusercontent.com/1507266/32953436-efefcb7a-cb8e-11e7-856b-e5866735dd92.png">

**Comment by dokterbob** [comment]
@newearthmartin Thanks a lot for the confirmation!

**Comment by dokterbob** [comment]
Just to be sure, this was current master, right?

**Comment by newearthmartin** [comment]
Yes

**Comment by ACPK** [comment]
Has this been fixed? This seems to be a major bug.

**Comment by dokterbob** [comment]
No, not fixed. Possibly the value of newsletter gets ignored in the create form.

Would greatly appreciate a fix, preferably before the next release. 
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by newearthmartin** [comment]
Hi! I found the cause of this bug. 

```
class Message(models.Model):
    ...
    def save(self, **kwargs):
        if self.pk is None:
            self.newsletter = Newsletter.get_default()
        super(Message, self).save(**kwargs)
    ...
```
So I wouldnt know why those lines are there in the first place???
so please check why and if possible remove them

**Comment by dokterbob** [comment]
It seems like a crappy way to set a default newsletter. Back in the days, we would do such stuff in the `save()` method. I *guess* we could maintain this functionality by setting `default=Newsletter.get_default` on `newsletter` in `Message` (and then removing this code).

What do you think? I'm kinda curious to see if you do that whether it will cause any tests to fail. If you think it won't and if you could do a little burn test as well (i.e. see if it doesn't break your setup) I would happily merge! :)

Thanks for spotting this one!

**Comment by newearthmartin** [comment]
Ok i tested in my setup and it works. Now I m running the tests.

It is failing because it expects the name of the message to be `'Test message'` and it is actually `'Test message in Test newsletter'`. This is actually correct because the newsletter is set since the message is created.

So I fix this and I then it fails in the next assertion `self.assertEqual(len(warnings), 1)` because warnings are zero. Would that be correct too?

**Comment by dokterbob** [comment]
I don't know. Any chance you could figure out what the original warning was? (i.e. by printing it)

Other than that your patch looks fine, will merge as soon as that part is done.

**Comment by newearthmartin** [comment]
yes!
> 'No newsletter has been set for this message yet.'


I added a migration which was missing, too
