### ISSUE TITLE
Accessing Newsletter models to automate email process

### ISSUE THREAD

**Issue by mihirsevak** [dokterbob/django-newsletter#234]
HI all,
     I am trying to do some automated things with newsletter app. In order to access all different tables such as newsletter_article, newsletter_message, newsletter_newsletter
,newsletter_submission, newsletter_subscription in database I am able to import their relevant models directly but for two tables namely newsletter_newsletter_site ,
newsletter_submission_subscriptions I am not able to import any models because they are many-to-many relations. How do I go about this?

Any help would be great.
Thanks.
Have a great day.

**Comment by dokterbob** [comment]
Hey,

Have no idea what you’re trying to import where, when, how and why. Also, I’m not a pro bono support desk. ;)

This really does sound like a Django issue, nothing at all to do with django-newsletter. You might want to ask your question at some mailinglist or Django’s IRC channel.

Good luck!
Mathijs
