### ISSUE TITLE
Django 1.8.13: TypeError, SubmissionArchiveDetailView returns template instead of string

### ISSUE THREAD

**Issue by romecode** [dokterbob/django-newsletter#236]
Request Method: | GET
-- | --
http://localhost:8000/newsletter/agf-weekly-newsletter/archive/2017/9/8/test/
1.8.13
TypeError
sequence item 0: expected string, Template found
/home/focus/git/django/django/template/loader.py in select_template, line 76
/home/focus/Dropbox/AGF_dev/venv/bin/python
2.7.11

Anyone else run into this?

**Comment by romecode** [comment]
Changing to get_template().origin fixes the issue but not sure on the dependencies

**Comment by romecode** [comment]
but doesnt work if debug=false

**Comment by romecode** [comment]
More updates: origin only works in debug mode, by django design.
Looks like the message preview is dependent on the actual template being returned, however, the django model views expect dir strings. the 2 are in disagreement afaict

**Comment by dokterbob** [comment]
@romecode Pretty sure, by now, this is a configuration issue. Could you confirm this so we can close the ticket? 

Thanks! :)
