### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by adi-** [dokterbob/django-newsletter#252]
My current email list counts 35k. It takes a lot of time to import those emails and most important, it takes a lot of time to add a new submission. I guess two things can be done:

1. add subscription groups
1. optimize subscription list in submission add admin view

**Comment by adi-** [comment]
Related to https://github.com/dokterbob/django-newsletter/issues/197

**Comment by dokterbob** [comment]
Newsletters, essentially, are already groups so it's not immediately clear what functionality this would add and - regardless - I don't think this pertains directly to the huge size of the list which is loaded in the browser.

With regards to the list, I would suggest integrating some kind of AJAX many to many selection, of which there are a bunch of implementations out there which could be considered. Alternatively, we could make manual selection an optional feature - which would align well with a feature request that has been asked for many times; default subscribers.

I would like to close this ticket now, as #197 already covers 2. (you are welcome to suggest an approach and/or implement it!) and you are welcome to create a new issue pertaining to 1. if you are able to make a good case for this functionality.
