### ISSUE TITLE
Per-subscription e-mail rendering (e.g. for personal unsubscribe link)

### ISSUE THREAD

**Issue by svdvonde** [dokterbob/django-newsletter#255]
I've only recently dived into Django-Newsletter so please forgive me if I have missed some features of the framework. 

If I am not mistaken, currently there is one e-mail being rendered and sent to users. It would be great if there was a way to render the newsletter on a per-subscription basis, gaining access to subscription context variables in the template. 

A possible use case is offering a personal unsubscribe link, such that users do not have to enter their own e-mailadres (which is pretty standard nowadays), or to offer one-click un-subscriptions (which is good practice).

**Comment by dokterbob** [comment]
It already works like this currently.

**Comment by svdvonde** [comment]
My apologies, I somehow completely missed that line in the documentation.

**Comment by mrxsal** [comment]
Perhaps another noobie question related to this, but it seems to me there is no subscription context variable available in the message.html template. 
![image](https://user-images.githubusercontent.com/39281049/114168156-2e590d00-9930-11eb-8b3f-757411caa217.png)

How would one go about with email personalization?
something like: Hi {{ user.first_name }} or, Hi {{ subscription.name }}
