### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by dokterbob** [dokterbob/django-newsletter#256]
Pending https://github.com/travis-ci/travis-ci/issues/9815 - as soon as Travis supports it we can re-enable tests and it might/should work.

**Comment by AndreGuerra123** [comment]
Looking into a workaround with `dist: xenial` and `sudo: yes` workaround. or otherwise this will stall with no 0.8 release will come soon. I have to depend on github source builds on every single project.

**Comment by dokterbob** [comment]
It seems the workaround was long since implemented:
https://github.com/dokterbob/django-newsletter/commit/d876b38292821fdedab65f2e63a6e02898a40325#diff-354f30a63fb0907d4ad57269548329e3. As a matter of fact, this is in 0.8b1 so you might install straight from pip.

But you're right, we might do a 0.8 stable release by now.

**Comment by gabn88** [comment]
Any news on this? (A)

**Comment by dokterbob** [comment]
I’ve been quite overwhelmed lately. If somebody volunteers to take over release engineering I’ll happily share the responsibility!

**Comment by gabn88** [comment]
My fingers are itching to make some changes, but it would be my first open source project. 
If you have a guide/how-to on how to work on this I would be happy to help.

Actually I'm using it now on Django 2.2 and python3.7 and it seems to work fine.

**Comment by dokterbob** [comment]
This is what I’m using 
https://github.com/dokterbob/django-newsletter/blob/master/RELENG.rst <https://github.com/dokterbob/django-newsletter/blob/master/RELENG.rst>
