### ISSUE TITLE
Permalink in newsletter/models.py

### ISSUE THREAD

**Issue by dkdndes** [dokterbob/django-newsletter#258]
Django 2.1 does not allow the use of permalink, it generates the following error:

```
newsletter/models.py", line 9, in <module>

from django.db.models import permalink
ImportError: cannot import name 'permalink
```

Please, have a look at
* [ticket/18974 ](https://code.djangoproject.com/ticket/18974)
* https://github.com/django/django/commit/4502489a466b89cccd9d2c1b8d21b2f153d71b4b

Maybe that is what you like to achieve:

```
    def get_absolute_url(self):
        return reverse('app_name_newsletter_detail', args=(self.pk,))

    def get_update_url(self):
        return reverse('app_name_newsletter_update', args=(self.pk,))
```

**Comment by AndreGuerra123** [comment]
I'm currently having this exact issue when installing through pip and following the installation guide on lts. How should it be solved? Regards

**Comment by dokterbob** [comment]
Thanks for reporting this. Has anyone tried Peter’s suggestion? If it works for you, could you please file a pull request so all the unittests get run?

**Comment by matheusjardimb** [comment]
Did this issue got solved? I still can reproduce it, just by upgrading to django==2.1.2;

Did django-newsletter got a new version? Is this fix available through pip?

**Comment by matheusjardimb** [comment]
Yet, the problem seems to get solved if I pip install directly from @AndreGuerra123 's repo (pip install git+https://github.com/AndreGuerra123/django-newsletter.git@master).

**Comment by matheusjardimb** [comment]
It may be missing a version bump/publish somehow?

**Comment by peter-doherty** [comment]
I installed via pip install django-newsletter and get this issue.

**Comment by dokterbob** [comment]
@peter-doherty Did you install the GitHub version? Note that the version on PIP does not support Django 2.1 just yet.

**Comment by peter-doherty** [comment]
Hi @dokterbob,

No, I used the pip version. Will try the GH version.

Thanks

**Comment by BeOleg** [comment]
getting it now with Django 2.2

**Comment by reyesvicente** [comment]
Getting the error on Django==2.2.5
