### ISSUE TITLE
[idea] checkbox to add to newsletter

### ISSUE THREAD

**Issue by willmendil** [dokterbob/django-newsletter#271]
You know what would be great? A way to add a check box in a form to automatically sign up for a newsletter after a contact form, for instance. Unless I'm mistaken, this option is not yet integrated, is it?

**Comment by dokterbob** [comment]
It's not and it won't.

But you are welcome to integrate it yourself, adding a NewsletterForm and possibly subclassing a SubscribeForm or something like that. If you do that, and add it to our documentation through a PR, I am sure it'll add great value!
