### ISSUE TITLE
subscription confirmation only sent as text

### ISSUE THREAD

**Issue by woodz-** [dokterbob/django-newsletter#272]
Although the newsletter mail itself is configured to send as html, the subscription confirmation mail is only sent as text. The newsletter mails itself are sent as html, all right.
Will the format of the subscription confirmation mail depend on the "sent html" setting in admin for a particular newsletter? Or is there a specific format setting for such subscription mails? Or am I missing something else?

**Comment by dokterbob** [comment]
To my knowledge all emails will be sent also as HTML, it's just there's no default HTML template for the templates might not be set.

Ref: https://github.com/dokterbob/django-newsletter/blob/master/newsletter/models.py#L353
