### ISSUE TITLE
Remove email address embedded into url format for update

### ISSUE THREAD

**Issue by kutenai** [dokterbob/django-newsletter#273]
The current "Action confirmation views" embed the email address into the URL. They also have the activation code, which is stored in the database (if I am not mistaken here).

For Analytics, this can leak Personally Identifiable Information (PII), which is a no-no in analytics.

I do not see what it is necessary to have the email in the URL, and for the above reason, quite desirable to NOT have it there. Is there a reason I am not aware of why this would be needed? If this is redundant information as I am thinking, it would be good to re-design the system to NOT require this, possibly leaving the URL definition there for 'legacy' or old emails sent out, but not sending out links with the email embedded in a future version.

**Comment by dokterbob** [comment]
Hi Ed,

Thanks for the feedback. This stuff was designed way before this type of analytics was around, let alone legislation on privacy.

I share your point, although I don’t think just the activation code is quite long enough to take away the chance for collissions. Hence, right now, it’s set up as a user-password type of challenge.

One possible solution would be to replace the email and significantly increase the length of the activation code - and to do lookups by that. What would you think about that? Would you be interested in implementing it?

**Comment by kutenai** [comment]
I would want to use a Universally Unique ID (UUID) for the code and remove the email. The UUID will never have a conflict, so it is a guaranteed solution, and never leaks any PII.

As far as implementing.., I certainly could. I'll create a fork and spend some time on it, but I have limited time, so can't guarantee a timeline. It is good to know that there is someone to pay attention, so if I dod submit a PR (with acceptable quality), it could actually get merged.

**Comment by kutenai** [comment]
I think the trick/issue would be how to do this in a backward compatible solution, or if a breaking change type solution might work.. probably not unless this is a major upgrade.

**Comment by dokterbob** [comment]
Perhaps make it a setting, defaulting to the original situation and deprecate the old behaviour.
In time, the new way will be the default.

**Comment by kutenai** [comment]
See my PR on this.
I made a backward compatible version that will take the old email format, but generate the new one for new action emails. 

I am assuming that users won't mind NOT having the email in there, as it was just to ensure uniqueness. The uuid does this without the email, which should be preferred.

**Comment by dokterbob** [comment]
Seems actually a dup of #183

Very useful discussion here, but closing for overview. We've got ourselves a PR, anyways :D
