### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by saileshkush95** [dokterbob/django-newsletter#278]
I didn't know why this is not working properly for me
![Screenshot from 2019-05-10 22-55-37](https://user-images.githubusercontent.com/28560875/57544436-0bee9b80-7377-11e9-9bb8-fc65d7cf66c4.png)

**Comment by dokterbob** [comment]
Please specify:

* What were you doing?
* What did you expect to happen.
* What happened instead.

Only that way we can help you!
