### ISSUE TITLE
Subscribing email creates 'Invalid input syntax for type inet' DataError with nginx/gunicorn

### ISSUE THREAD

**Issue by TravellerSam** [dokterbob/django-newsletter#279]
When set-up with gunicorn and nginx, the subscribe form throws a `DataError`:

<pre>
Traceback:

File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py" in _execute
  84.                 return self.cursor.execute(sql, params)

The above exception (ERROR:  invalid input syntax for type inet: »b''«
LINE 1: ...) VALUES (NULL, 'MyName', 'email@provider.com', 'b'''''::i...
                                                             ^
) was the direct cause of the following exception:

File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)
</pre>

It may be related to #226? My `/` nginx location has
`proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;` set. 

Subscribing a logged-in user works.

Versions: django newsletter 0.8b1, Django 2.2.2, Python 3.5.3, nginx 1.10.3, gunicorn3 19.6.0

**Comment by TravellerSam** [comment]
After an upgrade of a test VM to Debian 10 Buster bringing Python 3.7 the issue seem to be solved, but I need to test it yet. Would there be a fix for Python 3.5?

**Comment by woodz-** [comment]
When looking on the next [milestone](https://github.com/dokterbob/django-newsletter/milestones), neither Django > 2.0 nor Python 3.7 is supported. This might give any thoughts.
