### ISSUE TITLE
Interested in using this software

### ISSUE THREAD

**Issue by gcallah** [dokterbob/django-newsletter#285]
New York City government may want to adopt your software, but I am wondering if it is still actively being developed: I don't see any commits in almost a year.

**Comment by dokterbob** [comment]
Dear Gene,

Thanks for your question, which is very relevant. I haven’t had enough time to maintain it properly, but there are plenty of other contributors as well as users. Hence, if you suggest to use the software for a large client, I would suggest you take over the maintenance, or at least help me with it.

Does that sounds reasonable?

Mathijs

**Comment by dokterbob** [comment]
Contributor @gabn88 has offered to take over maintenance and release engineering. It would be great to have more developers on board, please let us know if you're still interested!

**Comment by gcallah** [comment]
Hi, we actually forked the repo and made modifications, the biggest being using tinymce as the mail editor. We are looking at implementing SAML. We are doing this work for New York City. If you'd like us to make a pull request, we can.

**Comment by dokterbob** [comment]
Hi Gene,

Thanks for getting back! Could you share the link of the fork?

I'd happily merge changes but would prefer to do so on a feature-by-feature base, to make sure your contributions make sense for other users and won't result in additional and/or dependencies maintenance on our side.

I don't quite understand what you imply by support for tinymce, to my best knowledge that is already configurable out of the box. I also don't really know how SAML integration would work, it seems something that would belong on the Django-auth side of things. But possibly there's something I'm missing.

In any case, great to hear our work is being used on such large scale. I'm honoured. :D

Mathijs
