### ISSUE TITLE
Django 2.2 and 3.0 Support

### ISSUE THREAD

**Issue by studybuffalo** [dokterbob/django-newsletter#291]
I am interested in using this for a project, but would want to have support for at least Django 2.2 (though 3 would be ideal). I am happy to do this work, but would just need to confirm someone is still active enough to release a new version when the work is done. I would also like to spend some time working through other issues and pull requests to help support the project.

Thanks in advance and for the excellent work on this project!

**Comment by dokterbob** [comment]
As a maintainer, I have sadly not been able to do much lately for personal reasons, but I have been talking to @gabn88 and others to see if we can transfer maintenance. We hope to be able to do so in the next few weeks, as you are totally right that this package deserves a Django 2.2 and 3.0 compatible release!

**Comment by studybuffalo** [comment]
That sounds great - thanks for the quick reply and no worries about competing priorities!

It turned out to be a pretty quick task to get the app running and passing all tests on Django 3.0. I want to do some clean up and refactor the impacted tests and then I will make a PR.

**Comment by dokterbob** [comment]
Great, thanks! Looking forward to the PR!

**Comment by dokterbob** [comment]
I've started work in #298 and have created separate issues for Django 1.11 #294, 2.2 #295 and 3.0 #296. It seems only 3.0 is causing issues, we'll have to replace sorl-thumbnail with something.

**Comment by studybuffalo** [comment]
Yes, I noticed the sorl-thumbnail issue as well. The repo itself is up-to-date and supports Django 3, but they haven't put out a new release yet. If we install the most recent version from the repo it seems to resolve the issues. I am hoping they do a new release in the very near future (they have a couple issues and pull requests in place already for this), which resolves the issue.

Alternatively, to avoid similar issues in the future, we could look at making this an optional dependency/feature to decouple the version compatibility issues?

**Comment by dokterbob** [comment]
I'm open to reducing hard drop dependencies but it requires some sound engineering. Don't have time for that myself but open to proposals.

Maybe a configurable image field? 
-- 
Enviado a partir do meu dispositivo Android com o K-9 Mail. Peço desculpa pela brevidade.

**Comment by dokterbob** [comment]
Closed in #300
