### ISSUE TITLE
Comma on line 588/589 of views.py

### ISSUE THREAD

**Issue by dalinxz** [dokterbob/django-newsletter#308]
Question about lines 588/589 of views.py:
`        context = \`
`            super(SubmissionArchiveDetailView, self).get_context_data(**kwargs)`

Is the \ intentional or is it intended to read?
        `context = super(SubmissionArchiveDetailView, self).get_context_data(**kwargs)`

**Comment by dokterbob** [comment]
It's a line break to make sure we comply with the PEP8 recommended max line width.

https://stackoverflow.com/questions/88942/why-does-pep-8-specify-a-maximum-line-length-of-79-characters
