### ISSUE TITLE
Idea: Document usage of mjml

### ISSUE THREAD

**Issue by gabn88** [dokterbob/django-newsletter#310]
I see myself using mjml (https://mjml.io/) a lot lately to create the .html templates for Django newsletter. By using visual studio code I have a live preview of how the mail will look like and the mail is compiled in a format usable by (almost) all email clients. Not that I'm involved in it or so, but I found it quite hard to write a good-looking email before, without using mailchimp or something similar.

**Comment by woodz-** [comment]
So what exactly is your idea here?
