### ISSUE TITLE
Make title optional

### ISSUE THREAD

**Issue by gabn88** [dokterbob/django-newsletter#313]
I think it would be good to make te title optional, not every bit of text in an email requires a title.

**Comment by woodz-** [comment]
From which title you are talking about? Can you be a bit more spcific?

**Comment by dokterbob** [comment]
I think actually providing a clear structure, making it easier for people to send *good* newsletters, is one of the particular features of django-newsletter. It's a matter of being opiniated. 

You are welcome to make a fork though! The moar forks the merrier! :)
