### ISSUE TITLE
For some reason, template is not overriden by custom file in project/newsletter/message/message.html (?)

### ISSUE THREAD

**Issue by HoshiYamazaki** [dokterbob/django-newsletter#318]
https://github.com/PSzczepanski996/django-newsletter.git
This is my custom fork I had to use for some of my own functionality - only one line of change, though.

For some reason when I try to use my script:
```
#!/usr/bin/env bash
cd /data/www/project
source /data/www/.virtualenvs/project/bin/activate
/data/www/project/manage.py $1 --settings=$2
```

And I am trying to send it via crontab on server, it doesn't use my custom template (WHY?).
I get error in `newsletter.log`:
```
The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG.
project.Category.subscribers: (fields.W340) null has no effect on ManyToManyField.
```

Which I don't quite understand, because I don't have any TEMPLATE_... setting(s) in my settings.py.

This is my crontab line:
```
0 * * * * /data/www/project/newsletter.sh submit_newsletter project.settings >> /data/www/project/logs/newsletter.log
```

`python manage.py submit_newsletter` works though normally.
Is this bash, django-newsletter, or bug releated to what module in my project/system?

**Comment by HoshiYamazaki** [comment]
My `pip freeze` packages:
```
django==1.11.20
django-mptt==0.9.0
mysqlclient==1.3.13
imagestore==3.1.0
sorl-thumbnail==12.5.0
django-recaptcha==1.2.0
django-extensions==1.7.5
surlex==0.2.0
django-ckeditor==5.6.1
django-haystack==2.8.1
whoosh==2.7.4
git+https://github.com/mobolic/facebook-sdk.git
tweepy==3.5.0
django-decorator-include==1.4.1
git+https://github.com/PSzczepanski996/xapian-haystack.git
git+https://github.com/PSzczepanski996/django-newsletter
```

**Comment by woodz-** [comment]
could you show us the contents of your script _/data/www/project/newsletter.sh_?

**Comment by woodz-** [comment]
then hard code `python manage.py submit_newsletter` in your script instead of making use of absolute path with parameters.
Make sure your are sourcing same envs.

**Comment by HoshiYamazaki** [comment]
I'm closing the issue, problem was that I had multiple instances connected to the same DB which was useless and causing template override (because some instances ran faster cron job than my desired).
