### ISSUE TITLE
Implement Ideas From Colossus

### ISSUE THREAD

**Issue by 9mido** [dokterbob/django-newsletter#321]
Maybe it would be a good idea for this project to implement some ideas from https://github.com/vitorfs/colossus since that is not actively maintained.

**Comment by dokterbob** [comment]
@9mido What ideas, specifically? Would appreciate separate issues for each one, so they can be efficiently discussed. Different contributors are usually only interested in particular features - and I myself am most unlikely to be able to implement any of them! ;)

**Comment by 9mido** [comment]
@dokterbob Good point I should have been more specific and will try to make separate issues when I have time! Thanks for being a cool maintainer :)
