### ISSUE TITLE
OAuth Support

### ISSUE THREAD

**Issue by astarrh** [dokterbob/django-newsletter#327]
While they have been temporarily delayed due to COVID, Google's plans are to [stop allowing remote apps to send email via smtp](https://gsuiteupdates.googleblog.com/2019/12/less-secure-apps-oauth-google-username-password-incorrect.html). 

I'm not sure how many users this would affect, but perhaps it would be useful to include support for [something like this](https://blog.macuyiko.com/post/2016/how-to-send-html-mails-with-oauth2-and-gmail-in-python.html) to allow mails to be sent through OAuth. Apologies if I missed this in the documentation.

**Comment by dokterbob** [comment]
Email sending is handled entirely through Django's email backend. If you're sending through Gmail (which I would highly recommend against, for newsletters - I would strongly recommend a specialised mail delivery service optimising for deliverability, like Sendgrid, Mailgun, Amazon SES), you should see whether you could configure Django to use that.
