### ISSUE TITLE
Captcha field

### ISSUE THREAD

**Issue by z3a** [dokterbob/django-newsletter#335]
Hy!

I'm wondering what is the correct way to implement a ReCaptcha field in the registration form for my mailing list without touch the django-newsletter codebase.

I'll appreciate any clues to do it.

Thanks in advance

**Comment by dokterbob** [comment]
You should be able to simply subclass the form and the form view and then mixin the captcha. 

Once you've done it, would really appreciate a PR for the docs, I'm sure other users will benefit. Thanks! Good luck!
